iopy: explicit error when trying to use an object from another plugin.
Before, the error was a bit cryptic when trying to use an object from
another plugin to create a new object from one other plugin:

  iopy.Error: error when parsing test.StructA: invalid argument `a`:
    invalid type: got test.ClassA (Struct test.ClassA:{'field1': 0}),
    expected StructBase (`test.ClassA`)

The issue comes from the fact that the plugins are isolated from one
another, and it is not possible to mix the classes.

Improve the error so it is much more understandable:

  iopy.Error: error when parsing test.StructA: invalid argument `a`:
    invalid type: got test.ClassA (Struct test.ClassA:{'field1': 0}),
    expected StructBase (`test.ClassA`); argument type `test.ClassA`
    comes from plugin '...test-iop-plugin2.so` (0x...), while expecting
    type `test.ClassA` from plugin `...test-iop-plugin.so` (0x...)'

Change-Id: If2e1a90f24c5e21619358628d2b1cd611576f960
Priv-Id: 1364cf9f3d9a27a711f431044f71ba18646ecca2