support gcc 8
False positives here in str-buf.h and str-l.h but gcc 8 found interesting
bugs in mmsx.

str-l.h:427:12: error: ‘memcmp’ specified size between
18446744071562067968 and 18446744073709551615 exceeds maximum object size
9223372036854775807 [-Werror=stringop-overflow=]
     return memcmp(s1.s, s2.s, len) ?: CMP(s1.len, s2.len);

str-buf.h:279:5: error: ‘memcpy’ forming offset [2, 20] is out of the
bounds [0, 1] of object ‘__sb_slop’ with type ‘const char[1]’
[-Werror=array-bounds]
     memcpy(sb_growlen(sb, dlen), data, dlen);

Change-Id: Id0c24f4c0a66d7f851dc6c7f30ca33960fb75263
(cherry picked from commit b28152e46a1f37a2103ead2f527281e850426d0d)

Conflicts:
	Config/cflags.sh
	str-l.h

rip-it: a0d64eb8c4bc1436df6e37b9d22ec7f4d8594f49 uprooted