tests/zparser: fix missing str() conversion
The time_as_str() method is failing in python 3 with this error:

    TypeError: unsupported format string passed to
    datetime.timedelta.__format__

The datetime.timedelta object must be converted to a string before
applying format().

Change-Id: Ia017d3ba440c35b14838803866716e4985623d6b
Priv-Id: 1cff61b618e0b76ef69ac68cfb95b7b498ca24d6