core-macros: Rename __flatten, __cold, __leaf and __fallthrough macros.
__leaf is conflicting with clang's pconfigintrin.h:

  /usr/lib/llvm-18/lib/clang/18/include/pconfigintrin.h:31:19: error: expected expression
   31 |            : "a" (__leaf), "b" (__d[0]), "c" (__d[1]), "d" (__d[2])
      |                   ^

So just like for the __unused__ macro in d7ed9d947aebba2c01c, rename
these so that we are hopefully not bothered in the future.

Change-Id: Id38b067894faf1c5a1acca1e42f818e1f0a6fb0a
Priv-Id: 05d52c1555a2160d84adb64b54de790aa0be98e0