core-macros: rename __unused__ to __attr_unused__
Our custom __unused__ macro is conflicting with some headers of the
glibc which use the syntax `__attribute__((__unused__))` in some places,
leading to compilation errors such as this one:

    [...]
    In file included from src/core/mem-fifo.c:19:
    In file included from ./lib-common/core.h:94:
    In file included from ./lib-common/core/errors.h:24:
    In file included from /usr/include/syslog.h:1:
    In file included from /usr/include/sys/syslog.h:207:
    /usr/include/bits/syslog.h:40:1: error: use of undeclared identifier 'unused' [Semantic Issue]
       40 | __fortify_function_error_function __attribute_overloadable__ void
          | ^
    /usr/include/sys/cdefs.h:221:66: note: expanded from macro '__fortify_function_error_function'
      221 | # define __fortify_function_error_function static __attribute__((__unused__))
          |                                                                  ^
    ./lib-common/core/macros.h:102:48: note: expanded from macro '__unused__'
      102 | # define __unused__             __attribute__((unused))
          |                                                ^
    [...]

To avoid this conflict we rename __unused__ to __attr_unused__. Note
that __unused__ was actually called __attr_unused__ in the documentation
because most of our custom attributes begin with __attr_ and it should
have been the case for __unused__ too.

Change-Id: Ie32e8547c26e532d496bf2619f0a9345501cac45
Priv-Id: d7ed9d947aebba2c01c76514f383d65d2d393569