cython: fix build with clang >= 15.
This is a adaptation of a642618d10d in r2022 that was actually removed
by 26c563b364e7 because it was thought to be unnecessary with the
changes in iopy in r2022 (2022.07 at the time).

But actually, it can happen on all cython modules:

[4301/4577] Linking one/minion.so
one/python_service.pyx.c:8033:77: error: parameter 'py_code' set but not used [-Werror,-Wunused-but-set-parameter,Semantic Issue]
static PyObject* __Pyx_Coroutine_patch_module(PyObject* module, const char* py_code) {
                                                                            ^
1 error generated.
Waf: Leaving directory `/home/buildbot/bb-rbx8-7_build/nightly_asan/build/.build-waf-asan'
Build failed
 -> task in 'python_service' failed with exit status 1 (run with -v to display more information)

To avoid this kind of issue, ignore the warning again on cython
generated code.

Change-Id: I1da211aac54b36816390512b6f841aec185d9cfb
Priv-Id: 2a2bba44485b7d46712db35bc7bfa38977c7f726