rust: add Python wrapper to convert `cargo test` output to Z protocol
Introduces `./build/tests/zcargo` script that converts `cargo test`'s
human-readable output to Z protocol, enabling seamless integration of
Rust unit tests into zchk tests.

Usage:
  ./build/tests/zcargo <pkg> [-- cargo test arguments]

Example:
```
    $ ./build/tests/zcargo.py zcargo

    1..5 unit-tests of `zcargo.rs` from pkg `zcargo` (cargo test)
    1 pass should_pass
    2 pass should_fail
    3 skip tests::should_skip
    4 pass tests::should_fail
    5 pass tests::should_pass
    # 20% skipped 80% passed 0% failed

    $ ./build/tests/zcargo.py zcargo -- --bin=zcargo-fail

    1..5 unit-tests of `zcargo-fail.rs` from pkg `zcargo` (cargo test)
    1 skip tests::should_skip
    2 fail should_fail
    :note: test did not panic as expected at rust/zcargo/zcargo-fail.rs:30:4
    3 fail tests::should_fail
    :note: test did not panic as expected at rust/zcargo/zcargo-fail.rs:43:8
    4 fail should_pass
    :
    :thread 'should_pass' panicked at rust/zcargo/zcargo-fail.rs:24:5:
    :assertion `left != right` failed
    :  left: 42
    : right: 42
    :note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    :
    5 fail tests::should_pass
    :
    :thread 'tests::should_pass' panicked at rust/zcargo/zcargo-fail.rs:38:9:
    :assertion `left != right` failed
    :  left: 42
    : right: 42
    :
    :
    # 20% skipped 0% passed 80% failed
```

Change-Id: Ic70420119201568160cb8b97e82a3507dc53c76d
Priv-Id: 10044a480bcca9d088fa1067698d4fe50bb0cba3