rust/doc: fix macros documentation links.
rustdoc needs to know the macros used in the example blocks.
Otherwise it fails with the following errors:
----
error: unresolved link to `c_module`
  --> rust/libcommon-core/module.rs:21:74
   |
21 | //! This module provides the [`ModuleBuilder`] builder pattern and the [`c_module!`] macro
   |                                                                          ^^^^^^^^^ no item named `c_module` in scope
----

This is done by adding some import and `#[doc(inline)]`.

Change-Id: I19784d2c173df4a92d9e87fd2057a1948ce54248
Priv-Id: 726e2a8f619a27a005be02f9b466103699a09fe5