tests/zparser: fix missing str() conversion
The time_as_str() method is failing in python 3 with this error:

    TypeError: unsupported format string passed to
    datetime.timedelta.__format__

The datetime.timedelta object must be converted to a string before
applying format().

(cherry picked from commit 1cff61b618e0b76ef69ac68cfb95b7b498ca24d6)
Change-Id: I8b63148ef6f5b6dfa0cb85fcf601810f504d8737
Priv-Id: 08156b290f70eed7aa4170124fc3f7e810d1af05