core/str: add explicit type cast to mp_lstr_dupz return value
The C++ compiler is failing to compile mmsx .blkk and .cc files with
-fpermissive flag. Here is a sample compilation error due to this:

In file included from platform/js/script-engine.blkk:42:
In file included from platform/lib-common/lib-common/el.h:33:
In file included from platform/lib-common/lib-common/core.h:104:
platform/lib-common/lib-common/core/str-l.h:175:12: error: cannot
initialize return object of type 'char * _Nonnull' with an rvalue of
type 'void * _Nonnull'
    return mp_dupz(mp, s.s, s.len);

This commit adds an explicit type cast to the problematic line above.

Change-Id: I40caf268456e1544334ccfa64c4dc4fa3f51eee5
Priv-Id: a3ef3c2e69e1d4fbaba216af0a29d3a07ab30ddd